name          'chriscowley-keybox'
version       '0.1.0'
source        'https://github.com/chriscowley/chriscowley-keybox.git'
author        'chriscowley'
license       'Apache 2.0'
summary       'Installs KeyBox a web-based SSH console'
description   ''
project_page  'https://github.com/chriscowley/chriscowley-keybox'

dependency 'puppetlabs/stdlib'
